DD.Electricity.Cloud.AuthServer/Models/Group/CreateGroupViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DD.Electricity.Cloud.AuthServer.Models.Group
{
    public class CreateGroupViewModel
    {
        [Display(Name ="集团名称")]
        [Required(ErrorMessage ="集团名称必填")]
        [MaxLength(16, ErrorMessage ="集团名称最大长度不能超过16")]
        public string GroupName { get; set; }

        [Display(Name = "行业")]
        [Required(ErrorMessage = "行业必填")]
        public string IndustryId { get; set; }
        public List<SelectListItem> Items { get; set; } = new List<SelectListItem>();
    }
}

DD.Electricity.Cloud.AuthServer/Models/Group/DisplayGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DD.Electricity.Cloud.AuthServer.Models.Group
{
    public class DisplayGroupViewModel
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string IndustryName { get; set; }
    }
}

DD.Electricity.Cloud.AuthServer/Models/Group/EditGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DD.Electricity.Cloud.AuthServer.Models.Group
{
    public class EditGroupViewModel : CreateGroupViewModel
    {
        public int Id { get; set; }
    }
}

DD.Electricity.Cloud.AuthServer/Controllers/GroupController.cs
using DD.Electricity.Cloud.AuthServer.Models;
using DD.Electricity.Cloud.AuthServer.Models.Group;
using DD.Electricity.Cloud.Domain.Entities.Headquarter;
using DD.Electricity.Cloud.HdPersistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace DD.Electricity.Cloud.AuthServer.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private HdDbContext _hdDbContext;
        public GroupController(HdDbContext hdDbContext)
        {
            _hdDbContext = hdDbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new List<DisplayGroupViewModel>();

            var dbGroups = _hdDbContext.Groups.Where(t => true).ToList();
            foreach (var dbGroup in dbGroups)
            {
                var item = new DisplayGroupViewModel();
                item.GroupName = dbGroup.Name;
                item.Id = dbGroup.Id;

                var dbIndustry = _hdDbContext.Industries.FirstOrDefault(t => t.Id == dbGroup.IndustryId);
                item.IndustryName = dbIndustry.Name;
                model.Add(item);

            }

            return View(model);
        }

        public IActionResult Create()
        {
            var model = new CreateGroupViewModel();
            model.Items = PopulateIndestries();


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateGroupViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Items = PopulateIndestries();
                return View(model);
            }

            if (model.IndustryId == "-1")
            {
                ModelState.AddModelError(string.Empty, "必须选择行业");
            }

            if(IsGroupNameExists(model.GroupName) ==false)
            {
                ModelState.AddModelError(string.Empty, "集团名称已经存在");
            }

            if (ModelState.ErrorCount > 0)
            {
                model.Items = PopulateIndestries();
                return View(model);
            }

            var dbGroup = new DD.Electricity.Cloud.Domain.Entities.Headquarter.Group();
            dbGroup.Name = model.GroupName;
            dbGroup.IndustryId = int.Parse(model.IndustryId);

            _hdDbContext.Groups.Add(dbGroup);
            _hdDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// 名称已经存在返回false
        /// </summary>
        /// <param name="groupName"></param>
        /// <returns></returns>
        private bool IsGroupNameExists(string groupName)
        {
            var dbGroup = _hdDbContext.Groups.FirstOrDefault(t => t.Name == groupName);
            return dbGroup == null ? true : false;
        }

        /// <summary>
        /// 存在返回false
        /// </summary>
        private bool IsGroupNameExistsByEdit(string groupName, int id)
        {
            var dbGroup = _hdDbContext.Groups.FirstOrDefault(t => t.Id != id && t.Name == groupName);
            return dbGroup == null ? true : false;
        }

        private List<SelectListItem> PopulateIndestries()
        {
            var result = new List<SelectListItem>();
            result.Add(new SelectListItem { Text = "---选择行业---", Value = "-1", Selected = true });
            result.AddRange(_hdDbContext.Industries.Where(t => t.ParentId != "-1").Select(t => new SelectListItem { Text = t.Name, Value = t.Id.ToString() }).ToList());

            return result;
        }

        private List<SelectListItem> PopulateIndustriesByEdit(int industryId)
        {
            var result = new List<SelectListItem>();
            result.Add(new SelectListItem { Text = "---选择行业---", Value = "-1", Selected = false });

            var dbIndustries = _hdDbContext.Industries.Where(t => t.ParentId != "-1");
            foreach (var dbIndustry in dbIndustries)
            {
                var item = new SelectListItem();
                item.Text = dbIndustry.Name;
                item.Value = dbIndustry.Id.ToString();
                item.Selected = industryId == dbIndustry.Id ? true : false;

                result.Add(item);
            }

            return result;
        }


        public IActionResult Edit(int id)
        {
            var model = new EditGroupViewModel();

            var dbGroup = _hdDbContext.Groups.FirstOrDefault(t => t.Id == id);
            model.Id = dbGroup.Id;
            model.GroupName = dbGroup.Name;
            model.Items = PopulateIndustriesByEdit(dbGroup.IndustryId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditGroupViewModel editGroupViewModel)
        {
            if (!ModelState.IsValid)
            {
                editGroupViewModel.Items = PopulateIndustriesByEdit(editGroupViewModel.Id);
                return View(editGroupViewModel);
            }

            if (editGroupViewModel.IndustryId == "-1")
            {
                ModelState.AddModelError(string.Empty, "必须选择行业");
            }

            if(IsGroupNameExistsByEdit(editGroupViewModel.GroupName, editGroupViewModel.Id)==false)
            {
                ModelState.AddModelError(string.Empty, "集团名称已经存在");
            }

            if(ModelState.ErrorCount>0)
            {
                editGroupViewModel.Items = PopulateIndustriesByEdit(editGroupViewModel.Id);
                return View(editGroupViewModel);
            }


            var dbGroup = _hdDbContext.Groups.FirstOrDefault(t => t.Id == editGroupViewModel.Id);
            var dbIndustry = _hdDbContext.Industries.FirstOrDefault(t => t.Id == int.Parse(editGroupViewModel.IndustryId));

            dbGroup.Name = editGroupViewModel.GroupName;
            dbGroup.IndustryId = dbIndustry.Id;
            dbGroup.Industry = dbIndustry;

            _hdDbContext.Update(dbGroup);
            await _hdDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var groups = await _hdDbContext.Groups.FirstOrDefaultAsync(m => m.Id == id);
        //    if (groups == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(groups);
        //}
    }
}




//[HttpGet]
//public IActionResult Edit(int? id)
//{
//    if(id==null)
//    {
//        return NotFound();
//    }

//    var groups = _hdDbContext.Groups.FirstOrDefault(t => t.Id == id);
//    var model = new GroupEditViewModel()
//    {
//        Id = groups.Id,
//        Name = groups.Name
//    };
//    return View(model);
//}
//[HttpPost]
//[ValidateAntiForgeryToken]
//public async Task<IActionResult> Edit(int id,[Bind("Id,Name")]GroupEditViewModel groupEditViewModel)
//{
//    if(id!=groupEditViewModel.Id)
//    {
//        return NotFound();
//    }
//    if(ModelState.IsValid)
//    {
//        try
//        {
//            _hdDbContext.Update(groupEditViewModel);
//            await _hdDbContext.SaveChangesAsync();

//        }
//        catch(DbUpdateConcurrencyException)
//        {
//            if(!GroupExists(groupEditViewModel.Id))
//            {
//                return NotFound();
//            }
//            else
//            {
//                throw;
//            }
//        }
//        return RedirectToAction(nameof(Index));
//    }
//    return View(groupEditViewModel);
//}


//        public async Task<IActionResult> Delete(int? id)
//        {
//            if (id == null)
//            {
//                return NotFound();
//            }

//            var groups = await _hdDbContext.Groups
//                .FirstOrDefaultAsync(m => m.Id == id);
//            if (groups == null)
//            {
//                return NotFound();
//            }

//            return View(groups);
//        }

//        // POST: Movices/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> DeleteConfirmed(int id)
//        {
//            var groups = await _hdDbContext.Groups.FindAsync(id);
//            _hdDbContext.Groups.Remove(groups);
//            await  _hdDbContext.SaveChangesAsync();
//            return RedirectToAction(nameof(Index));
//        }
//        private bool GroupExists(int id)
//        {
//            return _hdDbContext.Groups.Any(e => e.Id == id);
//        }
//    }
//}

DD.Electricity.Cloud.AuthServer/Views/Group/Create.cshtml
@model DD.Electricity.Cloud.AuthServer.Models.Group.CreateGroupViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Create Group</h1>
<hr />

<div class="container-fluid">
    <div class="row">
        <form method="post" asp-controller="Group" asp-action="Create" role="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="GroupName" class="control-label"></label>
                <input type="text" asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="IndustryId" class="control-label"></label>
                <select asp-items="@Model.Items" asp-for="IndustryId" class="form-control"></select>
                <span asp-validation-for="IndustryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
</div>
</div>

DD.Electricity.Cloud.AuthServer/Views/Group/Delete.cshtml
@model DD.Electricity.Cloud.Domain.Entities.Headquarter.Group
@{
    ViewData["Title"] = "Delete";
}
<h1>Delete</h1>
<h3>Are you sure you want to delte this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-action no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @Html.ActionLink("Back to List","Index")

        </div>
    }

</div>

DD.Electricity.Cloud.AuthServer/Views/Group/Details.cshtml
@model  DD.Electricity.Cloud.Domain.Entities.Headquarter.Group
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


<div>
    <h4>Group Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IndustryId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IndustryId)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">编辑</a>
    <a asp-action="Index">Back to List</a>
</div>

DD.Electricity.Cloud.AuthServer/Views/Group/Edit.cshtml
@model DD.Electricity.Cloud.AuthServer.Models.Group.EditGroupViewModel

@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.GroupName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GroupName)
            @Html.ValidationMessageFor(model => model.GroupName)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IndustryId, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select asp-for="IndustryId" asp-items="@Model.Items" class="form-control"></select>
            @Html.ValidationMessageFor(model => model.IndustryId)
        </div>
    </div>

    @*Genre and Price removed for brevity.*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="更改" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DD.Electricity.Cloud.AuthServer/Views/Group/Index.cshtml
@model IEnumerable<DD.Electricity.Cloud.AuthServer.Models.Group.DisplayGroupViewModel>
@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html>
<head></head>
<body>
<div class="container">
    <div class="row">
        <h1>Groups</h1>
    </div>
    <div>
        <h2>
            <a class="btn btn-primary" asp-controller="Group" asp-action="Create">创建Group</a>
        </h2>
    </div>
    <div class="row">
        <table class="table table-striped">
            <tr>
                <th>编号</th>
                <th>名称</th>
                <th>行业</th>
                <th>操作</th>
            </tr>
            @foreach (var item in Model)
            {
        <tr>
            <td>
            @Html.DisplayFor(modelItee => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItee => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IndustryName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">编辑</a>
                <a asp-action="Details" asp-route-id="@item.Id">详情</a>
                <a asp-action="Delete" asp-route-id="@item.Id">删除</a>
            </td>

        </tr>
            }

        </table>

    </div>
</div>
    </body>
</html>