DD.Electricity.Cloud.AuthServer/Controllers/DDAcountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DD.Electricity.Cloud.AuthServer.Data;
using DD.Electricity.Cloud.AuthServer.Data.Identity;
using DD.Electricity.Cloud.AuthServer.Models.DDAccount;
using DD.Electricity.Cloud.HdPersistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace DD.Electricity.Cloud.AuthServer.Controllers
{
    /// <summary>
    /// 鼎鼎账户管理
    /// </summary>
    [Authorize]
    public class DDAcountController : Controller
    {
        private readonly HdDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ApplicationDbContext _applicationDbContext;

        public DDAcountController(HdDbContext db, ApplicationDbContext applicationDbContext, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _applicationDbContext = applicationDbContext;
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var model = new List<DDIndexUserViewModel>();
            var users = _applicationDbContext.Users.Where(t => true).ToList();
            foreach(var user in users)
            {
                var groups = _db.Groups.FirstOrDefault(t => t.Id == int.Parse(user.GroupId));
                var item = new DDIndexUserViewModel();


                //_db.Projects.FirstOrDefault(t => t.Id == int.Parse(user.ProjectIds));
                //var dbProjectIds = new List<string>();

                string tempProjectNames = string.Empty;//存放拼接好的项目名称，以逗号分隔

                
                var projectIdLst = new List<string>(); //当前用户的选中项目主键集合
                if(!string.IsNullOrEmpty(user.ProjectIds))
                {
                    projectIdLst.AddRange(user.ProjectIds.Split(',').ToList());
                }

                var projectNameLst = new List<string>();//当前用户选中项目名称集合
                if(projectIdLst.Count>0)
                {
                    foreach(var projectId in projectIdLst)
                    {
                        var dbProject = _db.Projects.FirstOrDefault(t => t.Id == int.Parse(projectId));
                        projectNameLst.Add(dbProject.Name);
                    }
                }

                if(projectNameLst.Count>0)
                {
                    tempProjectNames = string.Join(',', projectNameLst);
                }
                
                item.ProjectName = tempProjectNames;


                item.Id = user.Id;
                //List<string> projectNames = new List<string>();
                //item.ProjectName = string.Join(",", projectNames.ToArray());
                item.UserName = user.UserName;
                item.GroupName = groups.Name;
                model.Add(item);
            }
            return View(model);
        }

        public IActionResult Create()
        {
            var model = new DDCreateUserViewModel();
            model.Groups = LoadGroups();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DDCreateUserViewModel model)
        {

            if(!ModelState.IsValid)
            {
                return View(model);
            }

            if(model.GroupId=="-1")
            {
                ModelState.AddModelError(string.Empty, "必须选择集团");
            }

            //创建用户
            var user = new ApplicationUser
            {
                UserName = model.UserName,
                GroupId = model.GroupId,
                ProjectIds = model.ProjectId
            };

            var createUserResult = await _userManager.CreateAsync(user, model.Password);
            if(!createUserResult.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "创建用户失败");
            }

            //创建角色
            //默认用户的角色是 DianGong
            var createRoleResult = await _userManager.AddToRoleAsync(user, "DianGong");
            if(!createRoleResult.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "创建用户角色失败");
            }

            if (ModelState.ErrorCount > 0)
            {
                return View(model);
            }


            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var model = new DDEditUserViewModel();

            var user = await _applicationDbContext.Users.FirstOrDefaultAsync(t => t.Id == id);
            //var users = await _userManager.GetUserAsync(User);
            //var groups = _db.Groups.FirstOrDefault(t => t.Id == int.Parse(users.GroupId));
            model.UserName = user.UserName;
            model.GroupId = user.GroupId;
            model.Groups = GroupByEdit(int.Parse(user.GroupId));
            model.Projects = GetProjectsbyGroupId(int.Parse(user.GroupId), user.ProjectIds);
            model.Password = user.PasswordHash;
            model.Id = user.Id;
            model.ProjectId = user.ProjectIds;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DDEditUserViewModel model)
        {
            //验证视图模型
            if(!ModelState.IsValid)
            {
                model.Groups= GroupByEdit(int.Parse(model.GroupId));
                model.Projects =GetProjectsbyGroupId(int.Parse(model.GroupId), model.ProjectId);
                return View(model);
            }

            //用户名重复不需要判断，因为界面已经禁止输入用户名
            //if(IsUserNameExitByEdit(model.UserName,int.Parse(model.Id))==false)
            //{
            //    ModelState.AddModelError(string.Empty, "用户名称已经存在");
            //}

            //找到用户
            var user = await _applicationDbContext.Users.FirstOrDefaultAsync(t => t.Id == model.Id);

            //var changePassword = await _userManager.ChangePasswordAsync(user,user.PasswordHash, model.Password);
            //if(!changePassword.Succeeded)
            //{
            //    ModelState.AddModelError(string.Empty, "修改密码失败");
            //}

            user.PasswordHash = _userManager.PasswordHasher.HashPassword(user, model.Password);
            user.GroupId = model.GroupId;
            user.ProjectIds = model.ProjectId;
            


            _applicationDbContext.Update(user);
            await _applicationDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
        private  bool IsUserNameExitByEdit(string UserName,int id)
        {
            var users = _applicationDbContext.Users.FirstOrDefault(t => int.Parse(t.Id) != id && t.UserName == UserName);
            return users == null ? true : false;
        }

        //public ActionResult GetProjectsByGroupId(string groupId, string userName="", string password="")
        //{
        //    var projects = _db.Projects.Where(t => t.GroupId == int.Parse(groupId));

        //    var tempProjects =new List<DDProjectCheckViewModel>();
        //    foreach(var project in projects)
        //    {
        //        var tempItem = new DDProjectCheckViewModel
        //        {
        //            Checked = false,
        //            Text = project.Name,
        //            Val = project.Id
        //        };

        //        tempProjects.Add(tempItem);
        //    }

        //    return RedirectToAction("Create", new { userName = userName, password = password, groupId = groupId, projects = tempProjects });
        //}
        private List<SelectListItem>GroupByEdit(int groupId)
        {
            var result = new List<SelectListItem>();
            result.Add(new SelectListItem { Text = "---选择集团---", Value = "-1", Selected = false });
            var dbGroup = _db.Groups.Where(t => true);
            foreach(var dbGroups in dbGroup)
            {
                var item = new SelectListItem();
                item.Text = dbGroups.Name;
                item.Value = dbGroups.Id.ToString();
                item.Selected = groupId == dbGroups.Id ? true : false;
                result.Add(item);
            }
            return result;
        }

        private List<SelectListItem> LoadGroups(string currentGroupId=null)
        {
            var result = new List<SelectListItem>();
            var dbGroups = _db.Groups.Where(t => true).ToList();
            if(string.IsNullOrEmpty(currentGroupId)) //创建用户显示集团
            {
                result.Add(new SelectListItem { Text = "---选择集团---", Value = "-1", Selected = true });
            }
            else //编辑用户显示集团
            {
                result.Add(new SelectListItem { Text = "---选择集团---", Value = "-1", Selected = false });
            }

            foreach(var group in dbGroups)
            {
                var item = new SelectListItem();
                item.Text = group.Name;
                item.Value = group.Id.ToString();
                item.Selected = !string.IsNullOrEmpty(currentGroupId) && currentGroupId == group.Id.ToString() ? true : false;

                result.Add(item);
            }
            return result;
        }

        /// <summary>
        /// 添加选择集团显示项目
        /// </summary>
        /// <param name="groupId"></param>
        /// <returns></returns>
        public IActionResult GetProjectsByGroup(string groupId)
        {
            List<DDProjectCheckViewModel> result = new List<DDProjectCheckViewModel>();
            var dbProjects = _db.Projects.Where(t => t.GroupId == int.Parse(groupId));
            foreach(var dbProject in dbProjects)
            {
                var item = new DDProjectCheckViewModel();

DD.Electricity.Cloud.AuthServer/Views/DDAcount/Create.cshtml
@model DD.Electricity.Cloud.AuthServer.Models.DDAccount.DDCreateUserViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create User</h2>

<div class="container-fluid">

        <form method="post" asp-controller="DDAcount" asp-action="Create" role="form" id="cform">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>@Html.HiddenFor(t=>t.ProjectId)</div>
            <div class="form-group row">
                <label asp-for="UserName" class="control-label"></label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="Password" class="control-label"></label>
                <input type="text" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-items="@Model.Groups" asp-for="GroupId" class="form-control"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group row" id="ProjectArea">
                @if(Model.Projects.Count>0)
                {
                    for(var i=0; i < Model.Projects.Count; i++)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @Html.CheckBoxFor(t=>Model.Projects[i].Checked)
                                @Html.HiddenFor(t=>t.Projects[i].Val)
                                <label>@Model.Projects[i].Text</label>
                            </div>
                        </div>
                    }
                }

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

</div>

@section Scripts{
    <script src="~/lib/jquery/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            //$('#ProjectArea').hide();
            //选择集团
            $('#GroupId').on('change', function () {
                var selectedVal = $(this).val();
                var userName = $('#UserName').val();
                var pass = $('#Password').val();
                if (selectedVal == -1) {//选择了选择集团
                    $('#ProjectArea').empty();
                }
                else {//选择了某个集团
                    $('#ProjectArea').load('/DDAcount/GetProjectsByGroup?groupId=' + selectedVal);
                }
            });

            var projectTempArr = [];
            //勾选某个项目
            $('#cform').on('change', '.projectCk', function () {

                projectTempArr = [];

                if ($("input:checkbox[name='ckprojects']:checked").length == 0) {
                    //alert('没有勾选了');
                    //projectTempArr = [];
                    $('#ProjectId').val('');
                    return;
                } else {
                    
                    $("input:checkbox[name='ckprojects']:checked").each(function () {
                        //每次遍历之前清空数组
                    
                        //获取Project主键
                        var projectId = $(this).parent().find('.project').val();
                        projectTempArr.push(projectId);
                    });
                }


                //如果临时数组不为空
                if (projectTempArr.length) {
                    var temp = projectTempArr.join(',');
                     $('#ProjectId').val(temp);
                }
           
            });

        });
    </script>
}

DD.Electricity.Cloud.AuthServer/Views/DDAcount/Edit.cshtml
@model DD.Electricity.Cloud.AuthServer.Models.DDAccount.DDEditUserViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<form asp-controller="DDAccount" asp-action="Edit" id="cform" method="post">

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div>@Html.HiddenFor(t => t.ProjectId)</div>

        <div class="form-group row">
            @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model=>model.UserName)*@
                <input class="form-control" asp-for="UserName" readonly />
                @Html.ValidationMessageFor(model => model.UserName)
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" asp-for="Password"  />
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        @*<div class="form-group row">
            @Html.LabelFor(model => model.NewPassword, new { @class="control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model=>model.NewPassword)
                @Html.ValidationMessageFor(model=>model.NewPassword)
            </div>
        </div>*@

        <div class="form-group row">
            @Html.LabelFor(model => model.GroupId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select asp-for="GroupId" asp-items="@Model.Groups" class="form-control"></select>
                @Html.ValidationMessageFor(model => model.GroupId)
            </div>
        </div>


        <div class="form-group row" id="ProjectArea">
            @if (Model.Projects.Count > 0)
            {
                for (var i = 0; i < Model.Projects.Count; i++)
                {
                    <div class="row">
                        <div class="col-md-12">
                            @Html.CheckBoxFor(t => Model.Projects[i].Checked)
                            @Html.HiddenFor(t => t.Projects[i].Val)
                            <label>@Model.Projects[i].Text</label>
                        </div>
                    </div>
                }
            }
        </div>
        <div class="form-group">
            <input type="submit" value="Edit" class="btn btn-primary" />
        </div>

    </div>
</form>

@section Scripts{
    <script src="~/lib/jquery/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            //$('#ProjectArea').hide();
            //选择集团
            $('#GroupId').on('change', function () {
                var selectedVal = $(this).val();
                var userName = $('#UserName').val();
                var pass = $('#Password').val();
                if (selectedVal == -1) {//选择了选择集团
                    $('#ProjectArea').empty();
                }
                else {//选择了某个集团
                    $('#ProjectArea').load('/DDAcount/GetProjectsByGroupEdit?groupId=' + selectedVal + '&projectIds=' + $('#ProjectId').val());
                }
            });

            var projectTempArr = [];
            //勾选某个项目
            $('#cform').on('change', '.projectCk', function () {

                projectTempArr = [];

                if ($("input:checkbox[name='ckprojects']:checked").length == 0) {
                    //alert('没有勾选了');
                    //projectTempArr = [];
                    $('#ProjectId').val('');
                    return;
                } else {

                    $("input:checkbox[name='ckprojects']:checked").each(function () {
                        //每次遍历之前清空数组

                        //获取Project主键
                        var projectId = $(this).parent().find('.project').val();
                        projectTempArr.push(projectId);
                    });
                }


                //如果临时数组不为空
                if (projectTempArr.length) {
                    var temp = projectTempArr.join(',');
                     $('#ProjectId').val(temp);
                }

            });

        });
    </script>
}

DD.Electricity.Cloud.AuthServer/Views/DDAcount/GetProjectsByGroup.cshtml
@model List< DD.Electricity.Cloud.AuthServer.Models.DDAccount.DDProjectCheckViewModel>

@{
    Layout = null;
}

@for(var i=0; i < Model.Count; i++)
{
    <div class="row">
        <div class="col-md-12">
            <div>
                <input type="checkbox" style="width:20px; height:20px" name="ckprojects"  asp-for="@Model[i].Checked" class="projectCk" />
                <input type="hidden" asp-for="@Model[i].Text" />
                <input type="hidden" asp-for="@Model[i].Val" class="project" />
                <label style="position:relative;top:-8px;right:-10px" asp-for="@Model[i].Checked">@Model[i].Text</label>
            </div>
        </div>
    </div>
}

DD.Electricity.Cloud.AuthServer/Views/DDAcount/GetProjectsByGroupEdit.cshtml
@model List<DD.Electricity.Cloud.AuthServer.Models.DDAccount.DDProjectCheckViewModel>

@{
    Layout = null;
}

@for (var i = 0; i < Model.Count; i++)
{
    <div class="row">
        <div class="col-md-12">
            <div>
                <input type="checkbox" style="width:20px; height:20px" name="ckprojects" asp-for="@Model[i].Checked" class="projectCk" />
                <input type="hidden" asp-for="@Model[i].Text" />
                <input type="hidden" asp-for="@Model[i].Val" class="project" />
                <label style="position:relative;top:-8px;right:-10px" asp-for="@Model[i].Checked">@Model[i].Text</label>
            </div>
        </div>
    </div>
}

DD.Electricity.Cloud.AuthServer/Views/DDAcount/Index.cshtml
@model IEnumerable<DD.Electricity.Cloud.AuthServer.Models.DDAccount.DDIndexUserViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Users</h1>
        </div>
        <div>
            <h2>
                <a class="btn btn-primary" asp-controller="DDAcount" asp-action="Create">增加新用户</a>
            </h2>
        </div>
        <div class="row">
            <table class="table table-striped">
                <tr>
                    <th>编号</th>
                    <th>用户名</th>
                    <th>集团名称</th>
                    <th>项目名称</th>
                    <th>操作</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItee => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItee => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItee => item.GroupName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProjectName)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">编辑</a>
                            <a asp-action="Details" asp-route-id="@item.Id">详情</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">删除</a>
                        </td>

                    </tr>
                }

            </table>

        </div>
    </div>
</body>
</html>