DD.Electricity.Cloud.AuthServer/Models/Account/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DD.Electricity.Cloud.AuthServer.Models.Account
{
    public class LoginViewModel
    {
        [Display(Name = "用户名")]
        [Required(ErrorMessage ="用户名必填")]
        [MaxLength(16, ErrorMessage ="用户名长度不能超过16")]
        public string UserName { get; set; }

        [Display(Name = "密码")]
        [Required(ErrorMessage = "密码必填")]
        [MaxLength(16, ErrorMessage = "密码长度不能超过16")]
        public string Passowrd { get; set; }
    }
}

DD.Electricity.Cloud.AuthServer/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DD.Electricity.Cloud.AuthServer.Data.Identity;
using DD.Electricity.Cloud.AuthServer.Models.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DD.Electricity.Cloud.AuthServer.Controllers
{
    [AllowAnonymous]
    public class SecurityController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public SecurityController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            //查找用户
            var user = await _userManager.FindByNameAsync(model.UserName);
            if(user==null)
            {
                ModelState.AddModelError(string.Empty, "用户名不存在");
                return View(model);
            }

            //登录
            var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Passowrd, false, false);
            if(!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "密码不正确");
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

DD.Electricity.Cloud.AuthServer/Views/Security/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AccessDenied</h2>

DD.Electricity.Cloud.AuthServer/Views/Security/Login.cshtml
@model DD.Electricity.Cloud.AuthServer.Models.Account.LoginViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h4>登录</h4>
                        <form class="form-group mt-3" asp-controller="Security" asp-action="Login" method="post">
                            <div class="input-group mb-3">
                                <span class="input-group-addon"><i class="glyphicon-user"></i></span>
                                <input type="text" class="form-control" asp-for="UserName" />
                            </div>
                            <div class="input-group mb-4">
                                <span class="input-group-addon"><i class="glyphicon-lock"></i></span>
                                <input type="text" class="form-control" asp-for="Passowrd" />
                            </div>
                            <div class="input-group mb-4 justify-content-center">
                                <button type="submit" class="btn px-4" >登录</button>
                            </div>
                            <div asp-validation-summary="All"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>